### ISSUE TITLE
osmosid autocomound error

### ISSUE THREAD

**Issue by BlockNgine** [eco-stake/restake#55] opened 2022-03-05 19:19 UTC
Finding delegators...
Checking 313 delegators for grants...
...batch 1
...batch 2
ERROR: Error: connect ETIMEDOUT 54.183.249.236:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1158:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.183.249.236',
  port: 443,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.26.0'
    },
    method: 'get',
    url: 'https://lcd-osmosis.blockapsis.com/cosmos/authz/v1beta1/grants?grantee=osmo194ytn50yhh67rdha8akhs7c6zulnz4n2pv6n63&granter=osmo159d5k2aaeepvxs3f7cv8uapeveh9a5shhu9amj',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/cosmos/authz/v1beta1/grants?grantee=osmo194ytn50yhh67rdha8akhs7c6zulnz4n2pv6n63&granter=osmo159d5k2aaeepvxs3f7cv8uapeveh9a5shhu9amj',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'lcd-osmosis.blockapsis.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/cosmos/authz/v1beta1/grants',
      search: '?grantee=osmo194ytn50yhh67rdha8akhs7c6zulnz4n2pv6n63&granter=osmo159d5k2aaeepvxs3f7cv8uapeveh9a5shhu9amj'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /cosmos/authz/v1beta1/grants?grantee=osmo194ytn50yhh67rdha8akhs7c6zulnz4n2pv6n63&granter=osmo159d5k2aaeepvxs3f7cv8uapeveh9a5shhu9amj HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.26.0\r\n' +
        'Host: lcd-osmosis.blockapsis.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/cosmos/authz/v1beta1/grants?grantee=osmo194ytn50yhh67rdha8akhs7c6zulnz4n2pv6n63&granter=osmo159d5k2aaeepvxs3f7cv8uapeveh9a5shhu9amj',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'lcd-osmosis.blockapsis.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://lcd-osmosis.blockapsis.com/cosmos/authz/v1beta1/grants?grantee=osmo194ytn50yhh67rdha8akhs7c6zulnz4n2pv6n63&granter=osmo159d5k2aaeepvxs3f7cv8uapeveh9a5shhu9amj',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by tombeynon** [comment] 2022-03-05 19:59
Similar/dupe of https://github.com/eco-stake/restake/issues/44, but Osmosis in this case.

We're relying on public nodes from the chain-registry by default, but you can change your local version of the networks.json file to only have your nodes in the `rpcUrl` and `restUrl` attributes of the networks you want to override. 

I'll raise an issue and have a look at a better local overrides solution. Validators should use their own nodes where possible.

**Comment by BlockNgine** [comment] 2022-03-06 06:58
I see thank you, we will use our own RPC servers

**Closed** 2022-03-06 06:58 UTC
